apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: fluxconfig
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: fluxconfig
spec:
  interval: 1m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: podinfo
  kubeConfig:
    secretRef:
      name: spoke-kubeconfig    
  path: "./kustomize"
  prune: true
  timeout: 1m
